site_name: 情報通信工学実験実習 II/III (情報工学) レポートの書き方
# theme: readthedocs
theme: material

nav:
  - Home: index.md

plugins:
  - search:
      lang: 'ja'
#  - with-pdf:
#      output_path: "docs.pdf"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
